language: ruby
install: gem install minitest
before_script:
  - gem build ci_uy.gemspec
  - gem install ci_uy
matrix:
  include:
    - os: linux
      dist: xenial
      rvm: 2.2
    - os: linux
      dist: xenial
      rvm: 2.3
    - os: linux
      dist: xenial
      rvm: 2.4
    - os: linux
      dist: xenial
      rvm: 2.5
    - os: linux
      dist: xenial
      rvm: 2.6
    - os: linux
      dist: xenial
      rvm: 2.7
    - os: linux
      dist: xenial
      rvm: jruby-19mode
    - os: linux
      dist: xenial
      rvm: jruby-head
    - os: linux
      dist: xenial
      rvm: ruby-head
    - os: linux
      dist: xenial
      rvm: truffleruby
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: truffleruby
