language: ruby
rvm:
  - 1.9.3
  - 2.1.10
  - 2.2.9
  - 2.3.8
  - 2.4.6
  - 2.5.5
  - 2.6.3
  - 2.7.0-preview1
  - jruby-19mode
  - jruby-head
  - ruby-head
  - rbx
install: gem install minitest
before_script:
  - gem build ci_uy.gemspec
  - gem install ci_uy
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx
